force-app/main/default/objects/Test_Governor_Limits__mdt/Test_Governor_Limits__mdt.object-meta.xml
<CustomObject>
    <description>This object defines governor limit requirements for your tests, allowing you to fine tune your tests efficiency.</description>
    <label>Test Governor Limits</label>
    <pluralLabel>Test Governor Limits</pluralLabel>
</CustomObject>

force-app/main/default/objects/Test_Governor_Limits__mdt/fields/Callouts_Limit__c.field-meta.xml
<CustomField>
    <fullName>Callouts_Limit__c</fullName>
    <description>Governor Limit for the Number of callouts in tests.</description>
    <inlineHelpText>Governor Limit for the Number of callouts in tests.</inlineHelpText>
    <label>Callouts Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Test_Governor_Limits__mdt/fields/CPU_Maximum_Limit__c.field-meta.xml
<CustomField>
    <fullName>CPU_Maximum_Limit__c</fullName>
    <description>Governor Limit for the Maximum CPU time in tests.</description>
    <inlineHelpText>Governor Limit for the Maximum CPU time in tests.</inlineHelpText>
    <label>CPU Maximum Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Test_Governor_Limits__mdt/fields/DML_Immediate_Limit__c.field-meta.xml
<CustomField>
    <fullName>DML_Immediate_Limit__c</fullName>
    <description>Governor Limit for the Number of Publish Immediate DML in tests.</description>
    <inlineHelpText>Governor Limit for the Number of Publish Immediate DML in tests.</inlineHelpText>
    <label>DML Immediate Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Test_Governor_Limits__mdt/fields/DML_Rows_Limit__c.field-meta.xml
<CustomField>
    <fullName>DML_Rows_Limit__c</fullName>
    <description>Governor Limit for the Number of DML rows in tests.</description>
    <inlineHelpText>Governor Limit for the Number of DML rows in tests.</inlineHelpText>
    <label>DML Rows Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Test_Governor_Limits__mdt/fields/DML_Statements_Limit__c.field-meta.xml
<CustomField>
    <fullName>DML_Statements_Limit__c</fullName>
    <description>Governor Limit for the Number of DML statements in tests.</description>
    <inlineHelpText>Governor Limit for the Number of DML statements in tests.</inlineHelpText>
    <label>DML Statements Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Test_Governor_Limits__mdt/fields/Email_Invocations_Limit__c.field-meta.xml
<CustomField>
    <fullName>Email_Invocations_Limit__c</fullName>
    <description>Governor Limit for the Number of Email Invocations in tests.</description>
    <inlineHelpText>Governor Limit for the Number of Email Invocations in tests.</inlineHelpText>
    <label>Email Invocations Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Test_Governor_Limits__mdt/fields/Future_Calls_Limit__c.field-meta.xml
<CustomField>
    <fullName>Future_Calls_Limit__c</fullName>
    <description>Governor Limit for the Number of future calls in tests.</description>
    <inlineHelpText>Governor Limit for the Number of future calls in tests.</inlineHelpText>
    <label>Future Calls Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Test_Governor_Limits__mdt/fields/Heap_Maximum_Limit__c.field-meta.xml
<CustomField>
    <fullName>Heap_Maximum_Limit__c</fullName>
    <description>Governor Limit for the Maximum heap size in tests.</description>
    <inlineHelpText>Governor Limit for the Maximum heap size in tests.</inlineHelpText>
    <label>Heap Maximum Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Test_Governor_Limits__mdt/fields/Mobile_Apex_Push_Calls_Limit__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Apex_Push_Calls_Limit__c</fullName>
    <description>Governor Limit for the Number of Mobile Apex push calls in tests.</description>
    <inlineHelpText>Governor Limit for the Number of Mobile Apex push calls in tests.</inlineHelpText>
    <label>Mobile Apex Push Calls Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Test_Governor_Limits__mdt/fields/Queueable_Jobs_Limit__c.field-meta.xml
<CustomField>
    <fullName>Queueable_Jobs_Limit__c</fullName>
    <description>Governor Limit for the Number of queueable jobs added to the queue in tests.</description>
    <inlineHelpText>Governor Limit for the Number of queueable jobs added to the queue in tests.</inlineHelpText>
    <label>Queueable Jobs Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Test_Governor_Limits__mdt/fields/SOQL_Queries_Limit__c.field-meta.xml
<CustomField>
    <fullName>SOQL_Queries_Limit__c</fullName>
    <description>Governor Limit for the Number of SOQL queries in tests.</description>
    <inlineHelpText>Governor Limit for the Number of SOQL queries in tests.</inlineHelpText>
    <label>SOQL Queries Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Test_Governor_Limits__mdt/fields/SOQL_Query_Rows_Limit__c.field-meta.xml
<CustomField>
    <fullName>SOQL_Query_Rows_Limit__c</fullName>
    <description>Governor Limit for the Number of query rows in tests.</description>
    <inlineHelpText>Governor Limit for the Number of query rows in tests.</inlineHelpText>
    <label>SOQL Query Rows Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Test_Governor_Limits__mdt/fields/SOSL_Queries_Limit__c.field-meta.xml
<CustomField>
    <fullName>SOSL_Queries_Limit__c</fullName>
    <description>Governor Limit for the Number of SOSL queries in tests.</description>
    <inlineHelpText>Governor Limit for the Number of SOSL queries in tests.</inlineHelpText>
    <label>SOSL Queries Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/TestLimitsChecker.cls
@IsTest
public class TestLimitsChecker {

    private static String TEST_GOVERNOR_LIMITS_SOBJECT_NAME = 'Test_Governor_Limits__mdt';
    private static String TEST_GOVERNOR_LIMITS_RECORD_DEVELOPER_NAME = 'Test_Governor_Limits';
    private static List<String> TEST_GOVERNOR_LIMITS_FIELDS = new List<String>{
        'CPU_Maximum_Limit__c', 
        'Callouts_Limit__c', 
        'DML_Immediate_Limit__c', 
        'DML_Rows_Limit__c', 
        'DML_Statements_Limit__c', 
        'Email_Invocations_Limit__c', 
        'Future_Calls_Limit__c', 
        'Heap_Maximum_Limit__c', 
        'Mobile_Apex_Push_Calls_Limit__c', 
        'Queueable_Jobs_Limit__c', 
        'SOQL_Queries_Limit__c', 
        'SOQL_Query_Rows_Limit__c', 
        'SOSL_Queries_Limit__c'
    };

    private static Test_Governor_Limits__mdt testGovernorLimits;

    private static String CHECK_LIMITS_EXCEPTION_MESSAGE = 'Please check the following governor limits for your test to improve performance: {0}';
    private class TestLimitsCheckerException extends Exception {}

    public static void runChecks() {
        getGovernorLimitsConfiguration();
        assertGovernorLimits();
    }

    private static void getGovernorLimitsConfiguration() {
        if (testGovernorLimits == null) {
            List<Test_Governor_Limits__mdt> testGovernorLimitsList = Database.query(
                'SELECT ' + String.join(TEST_GOVERNOR_LIMITS_FIELDS, ', ') + ' ' +
                'FROM ' + TEST_GOVERNOR_LIMITS_SOBJECT_NAME + ' ' +
                'WHERE DeveloperName = \'' + TEST_GOVERNOR_LIMITS_RECORD_DEVELOPER_NAME +'\''
            );

            if (!testGovernorLimitsList.isEmpty()) {
                testGovernorLimits = testGovernorLimitsList.get(0);
            }
        }
    }
    
    private static void assertGovernorLimits() {
        List<String> surpassedLimits = new List<String>();
        if (Limits.getCpuTime() > calculateMaximumAllowedLimit(Limits.getLimitCpuTime(), testGovernorLimits.CPU_Maximum_Limit__c)) {
            surpassedLimits.add('CPU');
        }
        if (Limits.getCallouts() > calculateMaximumAllowedLimit(Limits.getLimitCallouts(), testGovernorLimits.Callouts_Limit__c)) {
            surpassedLimits.add('Callouts');
        }
        if (Limits.getPublishImmediateDML() > calculateMaximumAllowedLimit(Limits.getLimitPublishImmediateDML(), testGovernorLimits.DML_Immediate_Limit__c)) {
            surpassedLimits.add('Publish Immediate DML');
        }
        if (Limits.getDmlRows() > calculateMaximumAllowedLimit(Limits.getLimitDmlRows(), testGovernorLimits.DML_Rows_Limit__c)) {
            surpassedLimits.add('DML Rows');
        }
        if (Limits.getDmlStatements() > calculateMaximumAllowedLimit(Limits.getLimitDmlStatements(), testGovernorLimits.DML_Statements_Limit__c)) {
            surpassedLimits.add('DML Statements');
        }
        if (Limits.getEmailInvocations() > calculateMaximumAllowedLimit(Limits.getLimitEmailInvocations(), testGovernorLimits.Email_Invocations_Limit__c)) {
            surpassedLimits.add('Email Invocations');
        }
        if (Limits.getFutureCalls() > calculateMaximumAllowedLimit(Limits.getLimitFutureCalls(), testGovernorLimits.Future_Calls_Limit__c)) {
            surpassedLimits.add('Future Calls');
        }
        if (Limits.getHeapSize() > calculateMaximumAllowedLimit(Limits.getLimitHeapSize(), testGovernorLimits.Heap_Maximum_Limit__c)) {
            surpassedLimits.add('Heap Size');
        }
        if (Limits.getMobilePushApexCalls() > calculateMaximumAllowedLimit(Limits.getLimitMobilePushApexCalls(), testGovernorLimits.Mobile_Apex_Push_Calls_Limit__c)) {
            surpassedLimits.add('Mobile Push Apex Calls');
        }
        if (Limits.getQueueableJobs() > calculateMaximumAllowedLimit(Limits.getLimitQueueableJobs(), testGovernorLimits.Queueable_Jobs_Limit__c)) {
            surpassedLimits.add('Queueable Jobs');
        }
        if (Limits.getQueries() > calculateMaximumAllowedLimit(Limits.getLimitQueries(), testGovernorLimits.SOQL_Queries_Limit__c)) {
            surpassedLimits.add('SOQL Queries');
        }
        if (Limits.getQueryRows() > calculateMaximumAllowedLimit(Limits.getLimitQueryRows(), testGovernorLimits.SOQL_Query_Rows_Limit__c)) {
            surpassedLimits.add('SOQL Query Rows');
        }
        if (Limits.getSoslQueries() > calculateMaximumAllowedLimit(Limits.getLimitSoslQueries(), testGovernorLimits.SOSL_Queries_Limit__c)) {
            surpassedLimits.add('SOSL Queries');
        }

        if (!surpassedLimits.isEmpty()) {
            String surpassedLimitsString = String.join(surpassedLimits, ', ');
            List<String> formatterParameters = new List<String>{surpassedLimitsString};
            throw new TestLimitsCheckerException(String.format(CHECK_LIMITS_EXCEPTION_MESSAGE, formatterParameters));
        }

    }

    private static Decimal calculateMaximumAllowedLimit(Integer platformGovernorLimit, Decimal allowedLimitPercentage) {
        return (platformGovernorLimit * allowedLimitPercentage / 100);
    }

}